spring:
  config:
    import:
      - 'classpath:adapter-http-property.yml'
      - 'classpath:adapter-persistence-property.yml'
      - 'classpath:adapter-redis-property.yml'
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: 38ff9ba7635ec7999af0c2c8aebe1d62
            client-secret: X0YU0vwTamliM6IwnQvng9Y9HxKn8Mg6
            client-name: Kakao
            authorization-grant-type: authorization_code
            redirect-uri: "http://localhost:3000/login/oauth2/code/kakao"
            scope: profile_nickname
            client-authentication-method: client_secret_post
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

jwt:
  secret: 677e35ebfd5e2619cec7c6b456bc2a6ba7ac74b2c3758cdb18617d340d9be1c2
  expire:
    access-token: 1
    refresh-token: 24
